print("Hello Dosto kya haal hai")
print("abcdefgh")
print("uday")
print("Hello Dosto kya haal hai")
print("abcdefgh")
print("uday")
print("Hello Dosto kya haal hai")
print("abcdefgh")
print("uday")
print("Hello Dosto kya haal hai")
print("abcdefgh")
print("uday")